owncloud:
  image: owncloud
  ports:
   - "80:80"
  links:
    - db
  environment:
  volumes:
    - /media/disk:/var/www/html/storage

db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=WONCLOUDRF#PTM
    - MYSQL_DATABASE=owncloud
